### ISSUE TITLE
Request Triage access for xiangzhu70 to the Solana Labs Monorepo

### ISSUE THREAD

**Issue by xiangzhu70** [solana-labs/contributor-access-policy#114]
### GitHub Username

xiangzhu70

### Discord ID

xiangzhu70#0432

**Comment by yihau** [comment]
Hi. Could you
1. replace [User] to your github username. (the title)
2. correct your discord id (should be xiangzhu70#0432 🤔)

**Comment by xiangzhu70** [comment]
> Hi. Could you
> 
> 1. replace [User] to your github username. (the title)
> 2. correct your discord id (should be xiangzhu70#0432 🤔)

Done.  Thanks!
