### ISSUE TITLE
Request Triage access for yhchiang-sol to the SPL repository

### ISSUE THREAD

**Issue by yhchiang-sol** [solana-labs/contributor-access-policy#119]
### GitHub Username

yhchiang-sol

### Discord ID

yhchiang.sol#0592

**Comment by CriesofCarrots** [comment]
@yhchiang-sol , can you please update the issue title to fill in [User]?

**Comment by joeaba** [comment]
@yhchiang-sol ping on this so we can proceed :)

**Comment by yhchiang-sol** [comment]
Done!

**Comment by CriesofCarrots** [comment]
I vouch for yhchiang-sol

**Comment by joncinque** [comment]
I vouch for yhchiang-sol

**Comment by joncinque** [comment]
@joeaba sorry about that! I thought I could trigger the pipeline

**Comment by CriesofCarrots** [comment]
> @joeaba sorry about that! I thought I could trigger the pipeline

You did! That joeaba was the bot :)
