### ISSUE TITLE
Access Level 2 for @willhickey to the Solana Labs Monorepo

### ISSUE THREAD

**Issue by willhickey** [solana-labs/contributor-access-policy#12]
### GitHub Username

@willhickey

### Discord ID

willhickey#2376

### Previously approved access level 1 issue

https://github.com/solana-labs/contributor-access-policy/issues/11

Edit: Added @ to username

**Comment by joeaba** [comment]
You missed your  [User] @willhickey

**Comment by willhickey** [comment]
Fixed

**Comment by joeaba** [comment]
I meant of the issue title hehe

**Comment by mvines** [comment]
I vouch for willhickey
