### ISSUE TITLE
Request Write access for jordansexton to the SPL repository

### ISSUE THREAD

**Issue by jordansexton** [solana-labs/contributor-access-policy#123]
### GitHub Username

jordansexton

### Discord ID

jordaaash#3040

### Previously approved Triage access request issue

https://github.com/solana-labs/contributor-access-policy/issues/65

**Comment by jordansexton** [comment]
This request is for occasional maintenance of SPL Token Lending and SPL Token (esp. JS libs, and some planned work on the Token 22 Confidential Extension).

**Comment by CriesofCarrots** [comment]
I vouch for jordansexton

**Comment by joncinque** [comment]
I vouch for jordansexton
