### ISSUE TITLE
Discord Access is not working

### ISSUE THREAD

**Issue by diman-io** [solana-labs/contributor-access-policy#129]
>Discord Access
>
>Any of the above access levels will grant you the Contributor role in the Solana Tech Discord server and a role tag with your current access level and the respective repository (e.g. SLP-Triage, Mono-Triage).

It appears that these steps are not working. [My request](https://github.com/solana-labs/contributor-access-policy/issues/122) [was processed](https://github.com/solana-labs/contributor-access-policy/issues/122#issuecomment-1452808218) by the bot 2 weeks ago.

**Comment by mvines** [comment]
@yihau - would you mind taking a look when you have a chance?

**Comment by yihau** [comment]
oh yeah. The discord role pipeline is still in the todo list 😢 we need to add it manually atm.

**Comment by yihau** [comment]
sorry for the late. this PR should solve this issue: https://github.com/solana-labs/contributor-access-policy/pull/137
