### ISSUE TITLE
Request Triage access for nickfrosty to the Solana Labs Monorepo

### ISSUE THREAD

**Issue by nickfrosty** [solana-labs/contributor-access-policy#130]
### GitHub Username

nickfrosty

### Discord ID

nickfrosty#7853

**Comment by steveluscher** [comment]
![7bcaf467-c327-45b3-a2df-a2f3ce5a3746_text](https://user-images.githubusercontent.com/13243/225777904-be3573ea-c614-4a85-a576-2b3f435e9ebd.gif)

**Comment by steveluscher** [comment]
![giphy](https://user-images.githubusercontent.com/13243/225779315-fa8edf47-a96e-4366-b11e-666a980ab89d.gif)

**Comment by steveluscher** [comment]
![57489126-62bb-4f9d-8358-e05b64043744_text](https://user-images.githubusercontent.com/13243/225779325-812736b5-0588-4863-be28-1c35cfecd5a6.gif)

**Comment by steveluscher** [comment]
I vouch for @nickfrosty.
