### ISSUE TITLE
Request Triage access for nickfrosty to the SPL repository

### ISSUE THREAD

**Issue by nickfrosty** [solana-labs/contributor-access-policy#131]
### GitHub Username

nickfrosty

### Discord ID

nickfrosty#7853

**Comment by nickfrosty** [comment]
@mvines @steveluscher

**Comment by steveluscher** [comment]
![658ec54a-5312-4ba5-94b0-a00fe5a36cdb_text](https://user-images.githubusercontent.com/13243/225777634-abba7bcd-82f8-466a-a4f0-200d2a6cd628.gif)
