### ISSUE TITLE
Request Triage access for musitdev to the Solana Labs Monorepo

### ISSUE THREAD

**Issue by musitdev** [solana-labs/contributor-access-policy#150]
### GitHub Username

musitdev

### Discord ID

philippe9088

**Comment by godmodegalactus** [comment]
I vouch for musitdev.

He has joined the mango team and will work on RPC v2.

**Comment by mvines** [comment]
per https://github.com/solana-labs/contributor-access-policy#level-1---triage-access, we need somebody with L2 to vouch. L1 can't vouch for L1

**Comment by KirillLykov** [comment]
I vouch for musitdev

**Comment by mvines** [comment]
@yihau - hey i forget what's next here, do we add a label and automation does it, or is a human required now?

**Comment by joeaba** [comment]
@mvines you just need to add the processing label and it'll kick in

**Comment by mvines** [comment]
halp, automation failed: https://github.com/solana-labs/contributor-access-policy/actions/runs/5627746801/job/15250760468

(not a weekend thing, next week totally fine!)

**Comment by joeaba** [comment]
rip, parsing failed cause he's using the old discord id format, will fix

**Comment by yihau** [comment]
@musitdev I can't find `philippe#9088` in our channel but I found this one

<img width="621" alt="Screenshot 2023-07-22 at 11 00 13 AM" src="https://github.com/solana-labs/contributor-access-policy/assets/8209234/2cbd6b29-91b3-4c6d-80c3-ac900c7177a6">

is this you?

**Comment by musitdev** [comment]
Yes it's me. I wasn't sure how discord ID are defined between the new name and the old id.
