### ISSUE TITLE
Request Write access for nickfrosty to the Solana Labs Monorepo

### ISSUE THREAD

**Issue by nickfrosty** [solana-labs/contributor-access-policy#153]
### GitHub Username

nickfrosty

### Discord ID

nick_frosty

### Previously approved Triage access request issue

https://github.com/solana-labs/contributor-access-policy/issues/130

**Comment by nickfrosty** [comment]
Vouchers from @joncinque and @buffalojoec 

Note: The current access list has a typo on both my github username and discord handle

**Comment by buffalojoec** [comment]
I vouch for @nickfrosty

**Comment by joeaba** [comment]
I vouch for @nickfrosty

**Comment by yihau** [comment]
hey. is this your account?
<img width="614" alt="Screenshot 2023-09-06 at 2 04 48 AM" src="https://github.com/solana-labs/contributor-access-policy/assets/8209234/5399d01e-492f-4a28-b0cb-0015dd721234">

**Comment by nickfrosty** [comment]
Yes it is!

**Comment by nickfrosty** [comment]
Jon is away for a few days. Request a voucher from @yihau?

**Comment by yihau** [comment]
updated acl manually https://github.com/solana-labs/contributor-access-policy/commit/801883d237114b06d466781707da813e06cc3f87
