### ISSUE TITLE
Request Write access for nickfrosty to the SPL repository

### ISSUE THREAD

**Issue by nickfrosty** [solana-labs/contributor-access-policy#155]
### GitHub Username

nickfrosty

### Discord ID

nick_frosty

### Previously approved Triage access request issue

https://github.com/solana-labs/contributor-access-policy/issues/131

**Comment by nickfrosty** [comment]
Vouchers from @joncinque and @buffalojoec

Note: The current access list has a typo on both my github username and discord handle

**Comment by buffalojoec** [comment]
I vouch for @nickfrosty

**Comment by joeaba** [comment]
I vouch for @nickfrosty

**Comment by nickfrosty** [comment]
Jon is away for a few days. Request a voucher from @yihau?

**Comment by yihau** [comment]
updated acl manually https://github.com/solana-labs/contributor-access-policy/commit/801883d237114b06d466781707da813e06cc3f87
