### ISSUE TITLE
Request Write access for lorisleiva to the SPL repository

### ISSUE THREAD

**Issue by steveluscher** [solana-labs/contributor-access-policy#158]
### GitHub Username

lorisleiva

### Discord ID

loris5388

### Previously approved Triage access request issue

https://github.com/solana-labs/contributor-access-policy/issues/157

**Comment by steveluscher** [comment]
I support the promotion of lorisleiva to Write-SPL so that he can start the process of unbundling Solana programs into separate repositories.

**Comment by joncinque** [comment]
I vouch for Loris
