### ISSUE TITLE
Access Level 2 for dmakarov to the Solana Labs Monorepo

### ISSUE THREAD

**Issue by dmakarov** [solana-labs/contributor-access-policy#17]
### GitHub Username

dmakarov

### Discord ID

dmakarov#2519

### Previously approved access level 1 issue

https://github.com/solana-labs/contributor-access-policy/issues/15

**Comment by joeaba** [comment]
I vouch for dmakarov

**Comment by mvines** [comment]
I vouch for dmakarov
