### ISSUE TITLE
Access Level 2 for lijunwangs to the Solana Labs Monorepo

### ISSUE THREAD

**Issue by lijunwangs** [solana-labs/contributor-access-policy#32]
### GitHub Username

lijunwangs

### Discord ID

lijunwangs#4818

### Previously approved access level 1 issue

[27](https://github.com/solana-labs/contributor-access-policy/issues/27)

**Comment by mvines** [comment]
I vouch for lijunwangs

**Comment by CriesofCarrots** [comment]
I vouch for lijunwangs
