### ISSUE TITLE
Access Level 2 for bw-solana to the Solana Labs Monorepo

### ISSUE THREAD

**Issue by bw-solana** [solana-labs/contributor-access-policy#36]
### GitHub Username

bw-solana

### Discord ID

bw#0480

### Previously approved access level 1 issue

https://github.com/solana-labs/contributor-access-policy/issues/34

**Comment by CriesofCarrots** [comment]
I vouch for bw-solana

**Comment by joeaba** [comment]
I vouch for bw-solana
