### ISSUE TITLE
Access Level 2 for [taozhu-chicago] to the Solana Labs Monorepo

### ISSUE THREAD

**Issue by taozhu-chicago** [solana-labs/contributor-access-policy#42]
### GitHub Username

taozhu-chicago

### Discord ID

Tao#2945

### Previously approved access level 1 issue

https://github.com/solana-labs/contributor-access-policy/issues/38

**Comment by joeaba** [comment]
I vouch for taozhu-chicago

**Comment by CriesofCarrots** [comment]
I vouch for taozhu-chicago
