### ISSUE TITLE
Access Level 2 for IntokuSatori to the Solana Labs Monorepo

### ISSUE THREAD

**Issue by IntokuSatori** [solana-labs/contributor-access-policy#46]
### GitHub Username

IntokuSatori

### Discord ID

IntokuSatori#7070

### Previously approved access level 1 issue

https://github.com/solana-labs/contributor-access-policy/issues/44

**Comment by joeaba** [comment]
I vouch for IntokuSatori

**Comment by mvines** [comment]
I vouch for IntokuSatori
