### ISSUE TITLE
Access Level 2 for IntokuSatori to the SPL repository

### ISSUE THREAD

**Issue by IntokuSatori** [solana-labs/contributor-access-policy#47]
### GitHub Username

IntokuSatori

### Discord ID

IntokuSatori#7070

### Previously approved access level 1 issue

https://github.com/solana-labs/contributor-access-policy/issues/45

**Comment by joeaba** [comment]
I vouch for IntokuSatori

**Comment by mvines** [comment]
I vouch for IntokuSatori
