### ISSUE TITLE
Access Level 2 for ngundotra to the SPL repository

### ISSUE THREAD

**Issue by ngundotra** [solana-labs/contributor-access-policy#48]
### GitHub Username

ngundotra

### Discord ID

nundox#3873

### Previously approved access level 1 issue

https://github.com/solana-labs/contributor-access-policy/issues/26

**Comment by joeaba** [comment]
I vouch for ngundotra

**Comment by joncinque** [comment]
I vouch for ngundotra

**Comment by joncinque** [comment]
Done
