### ISSUE TITLE
Access Level 2 for jeffwashington to the Solana Labs Monorepo

### ISSUE THREAD

**Issue by jeffwashington** [solana-labs/contributor-access-policy#56]
### GitHub Username

jeffwashington

### Discord ID

jwash#5045

### Previously approved access level 1 issue

https://github.com/solana-labs/contributor-access-policy/issues/53

**Comment by joeaba** [comment]
I vouch for jeffwashington

**Comment by CriesofCarrots** [comment]
I vouch for jeffwashington
