### ISSUE TITLE
Access Level 2 for jbiseda to the Solana Labs Monorepo

### ISSUE THREAD

**Issue by jbiseda** [solana-labs/contributor-access-policy#57]
### GitHub Username

jbiseda

### Discord ID

jbiseda#8785

### Previously approved access level 1 issue

https://github.com/solana-labs/contributor-access-policy/issues/52

**Comment by joeaba** [comment]
I vouch for jbiseda

**Comment by CriesofCarrots** [comment]
I vouch for jbiseda
