### ISSUE TITLE
Access Level 2 for ilya-bobyr to the Solana Labs Monorepo

### ISSUE THREAD

**Issue by ilya-bobyr** [solana-labs/contributor-access-policy#59]
### GitHub Username

ilya-bobyr

### Discord ID

illia-bobyr#4223

### Previously approved access level 1 issue

https://github.com/solana-labs/contributor-access-policy/issues/54

**Comment by CriesofCarrots** [comment]
I vouch for I vouch for ilya-bobyr

**Comment by mvines** [comment]
I vouch for @ilya-bobyr
