### ISSUE TITLE
Access Level 2 for HaoranYi to the Solana Labs Monorepo

### ISSUE THREAD

**Issue by HaoranYi** [solana-labs/contributor-access-policy#62]
### GitHub Username

HaoranYi

### Discord ID

haoranyi

### Previously approved access level 1 issue

https://github.com/solana-labs/contributor-access-policy/issues/24

**Comment by CriesofCarrots** [comment]
I vouch for haoranyi

**Comment by mvines** [comment]
I vouch for HaoranYi
