### ISSUE TITLE
Request Write access for [joncinque] to the Solana Labs Monorepo

### ISSUE THREAD

**Issue by joncinque** [solana-labs/contributor-access-policy#83]
### GitHub Username

joncinque

### Discord ID

jon#1892

### Previously approved Triage access request issue

https://github.com/solana-labs/contributor-access-policy/issues/64

**Comment by yihau** [comment]
I vouch for @joncinque

**Comment by joeaba** [comment]
I vouch for joncinque

**Comment by joncinque** [comment]
@joeaba sorry for the ping, but it looks like I was removed from triage and never added to write https://github.com/orgs/solana-labs/teams/monorepo-write/members

**Comment by joeaba** [comment]
fixed!
