### ISSUE TITLE
Request Write access for samkim-crypto to the SPL repository

### ISSUE THREAD

**Issue by samkim-crypto** [solana-labs/contributor-access-policy#89]
### GitHub Username

samkim-crypto

### Discord ID

SamKim#2012

### Previously approved Triage access request issue

https://github.com/solana-labs/contributor-access-policy/issues/72

**Comment by CriesofCarrots** [comment]
I vouch for samkim-crypto

**Comment by joncinque** [comment]
I vouch for samkim-crypto
