### ISSUE TITLE
Access Level 2 for brooksprumo to the Solana Labs Monorepo

### ISSUE THREAD

**Issue by brooksprumo** [solana-labs/contributor-access-policy#9]
### GitHub Username

brooksprumo

### Discord ID

brooks#7217

### Previously approved access level 1 issue

https://github.com/solana-labs/contributor-access-policy/issues/7

**Comment by joeaba** [comment]
I vouch for brooksprumo

**Comment by mvines** [comment]
I vouch for brooksprumo
