### ISSUE TITLE
Request Write access for apfitzge to the SPL repository

### ISSUE THREAD

**Issue by apfitzge** [solana-labs/contributor-access-policy#98]
### GitHub Username

apfitzge

### Discord ID

andrew.fitzgerald#1084

### Previously approved Triage access request issue

https://github.com/solana-labs/contributor-access-policy/issues/97

**Comment by CriesofCarrots** [comment]
I vouch for apfitzge

**Comment by yihau** [comment]
I vouch for apfitzge
